### ISSUE TITLE
License

### ISSUE THREAD

**Issue by amis92** [dsantarelli/TextTableFormatter.NET#1]
Hi, I wanted to use this library (and maybe fork it and make some changes) but there's no license specified. Is there any chance to add one if you deem so appropriate? I'd love it to be MIT, Apache 2.0 (that's the one the Java original uses) or some other popular open-source one; but currently it only specifies your copyright in AssemblyInfo :)

Thanks in advance.

**Comment by dsantarelli** [comment]
Hi, sorry for the late answer.
The license is [Apache v2.0](https://github.com/dsantarelli/TextTableFormatter.NET/blob/master/LICENSE.md) (the same you can find in [the original Java project](https://sourceforge.net/projects/texttablefmt/)).

Best regards
